<?php

/**
 * @file
 * Helps site builders and module developers investigate the site.
 *
 */

/**
 * Implements hook_form_alter() to show each form's identifier
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */

function xray_form_alter(&$form, &$form_state, $form_id) {
  $form['xray_display_form_id'] = array(
    '#type' => 'item',
    '#title' => t('Form ID'),
    '#markup' => $form_id,
    '#weight' => -100,
  );
}

/**
 * Implements hook_help()
 */

function xray_help($path, $arg) {
  if ($path == 'admin/content') {
    return t('hello jello');
  }
}
